name: build_flow

on:
  push:
    branches:
      - master

jobs:
  define_semver:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Check Git Version
        id: version
        uses: codacy/git-version@2.4.0
